services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - libretranslate_models:/home/libretranslate/.local:rw
  
  opentts:
    image: synesthesiam/opentts:latest
    ports:
      - "5500:5500"
    restart: unless-stopped

volumes:
  libretranslate_models:
